/**
 * Review-package renderers: structured extract → human-readable markdown with
 * embedded Mermaid diagrams.
 *
 * Output is deterministic given the same extract input (modulo the timestamp
 * line). No LLM calls. Safe to re-run; safe to regenerate after spec edits.
 */

import type {
  SystemExtract,
  SubsystemExtract,
  ComponentExtract,
  IntegrationExtract,
} from './extract.js';
import { splitContractParties } from './extract.js';

// ═══════════════════════════════════════════════════════════════════════
//  Mermaid sanitization
// ═══════════════════════════════════════════════════════════════════════

/**
 * Mermaid node ids must be [A-Za-z][A-Za-z0-9_]* for reliable rendering.
 * Spec component names may contain spaces, dashes, or punctuation — sanitize
 * them into safe identifiers and keep the original as a label.
 */
function toNodeId(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_').replace(/_+/g, '_');
  if (/^[A-Za-z]/.test(cleaned)) return cleaned;
  return 'N_' + cleaned; // prefix if starts with digit or underscore
}

/** Escape quotes for Mermaid label strings. */
function labelSafe(s: string): string {
  return s.replace(/"/g, '\\"').replace(/\n/g, ' ');
}

// ═══════════════════════════════════════════════════════════════════════
//  System review
// ═══════════════════════════════════════════════════════════════════════

export function renderSystemReview(extract: SystemExtract, specPath: string): string {
  const { title, overview, subsystems, nfr, warnings } = extract;

  const lines: string[] = [];
  lines.push(`# ${title} — Review Summary`);
  lines.push('');
  lines.push(`_Auto-generated by spec2 review. Full spec: \`${specPath}\`_`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(overview || '_(No overview extracted from spec.)_');
  lines.push('');
  lines.push('## Key Facts');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| Subsystems | ${subsystems.length} |`);
  for (const [k, v] of Object.entries(nfr)) {
    lines.push(`| NFR — ${k} | ${escapePipes(v)} |`);
  }
  lines.push('');
  lines.push('## Subsystem Map');
  lines.push('');
  lines.push('```mermaid');
  lines.push(buildSystemMermaid(extract));
  lines.push('```');
  lines.push('');
  lines.push('## Subsystems');
  lines.push('');
  if (subsystems.length === 0) {
    lines.push('_(No subsystems extracted.)_');
  } else {
    for (const s of subsystems) {
      lines.push(`### ${s.name}`);
      if (s.purpose) lines.push(`**Purpose:** ${s.purpose}`);
      if (s.responsibilities.length > 0) {
        lines.push('');
        lines.push('Responsibilities:');
        for (const r of s.responsibilities) lines.push(`- ${r}`);
      }
      lines.push('');
    }
  }
  appendWarnings(lines, warnings);
  return lines.join('\n');
}

function buildSystemMermaid(x: SystemExtract): string {
  const out: string[] = ['graph TD'];
  const root = toNodeId('System');
  out.push(`  ${root}["${labelSafe(x.title)}"]`);
  for (const s of x.subsystems) {
    const nid = toNodeId(s.name);
    out.push(`  ${nid}["${labelSafe(s.name)}"]`);
    out.push(`  ${root} --> ${nid}`);
  }
  if (x.subsystems.length === 0) {
    out.push('  %% No subsystems extracted');
  }
  return out.join('\n');
}

// ═══════════════════════════════════════════════════════════════════════
//  Subsystem review
// ═══════════════════════════════════════════════════════════════════════

export function renderSubsystemReview(extract: SubsystemExtract, specPath: string): string {
  const { name, overview, components, dependencies, testStrategy, warnings } = extract;

  const lines: string[] = [];
  lines.push(`# Subsystem: ${name} — Review Summary`);
  lines.push('');
  lines.push(`_Auto-generated by spec2 review. Full spec: \`${specPath}\`_`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(overview || '_(No overview extracted.)_');
  lines.push('');
  lines.push('## Key Facts');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| Components | ${components.length} |`);
  lines.push(`| External dependencies | ${dependencies.length} |`);
  lines.push('');
  lines.push('## Composition');
  lines.push('');
  lines.push('```mermaid');
  lines.push(buildSubsystemMermaid(extract));
  lines.push('```');
  lines.push('');

  lines.push('## Components');
  lines.push('');
  if (components.length === 0) {
    lines.push('_(No components extracted.)_');
  } else {
    for (const c of components) {
      lines.push(`- **${c.name}**${c.description ? ` — ${c.description}` : ''}`);
    }
  }
  lines.push('');

  lines.push('## Dependencies');
  lines.push('');
  if (dependencies.length === 0) {
    lines.push('_(No external dependencies declared.)_');
  } else {
    lines.push('| From | What | Contract |');
    lines.push('|------|------|----------|');
    for (const d of dependencies) {
      lines.push(`| ${escapePipes(d.from)} | ${escapePipes(d.what)} | ${escapePipes(d.contract)} |`);
    }
  }
  lines.push('');

  if (testStrategy) {
    lines.push('## Test Strategy');
    lines.push('');
    lines.push(testStrategy);
    lines.push('');
  }

  appendWarnings(lines, warnings);
  return lines.join('\n');
}

function buildSubsystemMermaid(x: SubsystemExtract): string {
  const out: string[] = ['graph TD'];
  const sub = toNodeId(x.name || 'Subsystem');
  out.push(`  subgraph ${sub}["${labelSafe(x.name)}"]`);
  for (const c of x.components) {
    const cid = toNodeId(c.name);
    out.push(`    ${cid}["${labelSafe(c.name)}"]`);
  }
  if (x.components.length === 0) {
    out.push('    %% No components extracted');
  }
  out.push('  end');
  // External deps flow INTO the subsystem
  const seenExt = new Set<string>();
  for (const d of x.dependencies) {
    const ext = toNodeId(d.from);
    if (!seenExt.has(ext) && d.from !== x.name) {
      out.push(`  ${ext}[["${labelSafe(d.from)}"]]`);
      out.push(`  ${ext} -->|"${labelSafe(d.what)}"| ${sub}`);
      seenExt.add(ext);
    }
  }
  return out.join('\n');
}

// ═══════════════════════════════════════════════════════════════════════
//  Component review
// ═══════════════════════════════════════════════════════════════════════

export function renderComponentReview(extract: ComponentExtract, specPath: string): string {
  const { name, overview, types, functions, imports, exports, warnings } = extract;

  const lines: string[] = [];
  lines.push(`# Component: ${name} — Review Summary`);
  lines.push('');
  lines.push(`_Auto-generated by spec2 review. Full spec: \`${specPath}\`_`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(overview || '_(No overview extracted.)_');
  lines.push('');
  lines.push('## Key Facts');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| Functions | ${functions.length} |`);
  lines.push(`| Types | ${types.length} |`);
  lines.push(`| Imports | ${imports.length} |`);
  lines.push(`| Exports | ${exports.length} |`);
  lines.push('');

  lines.push('## Structure');
  lines.push('');
  lines.push('```mermaid');
  lines.push(buildComponentMermaid(extract));
  lines.push('```');
  lines.push('');

  if (functions.length > 0) {
    lines.push('## Public Functions');
    lines.push('');
    for (const f of functions) {
      lines.push(`- \`${f.signature}\`${f.purpose ? ` — ${f.purpose}` : ''}`);
    }
    lines.push('');
  }

  if (types.length > 0) {
    lines.push('## Types');
    lines.push('');
    for (const t of types) {
      lines.push(`- **${t.name}**${t.purpose ? ` — ${t.purpose}` : ''}`);
    }
    lines.push('');
  }

  if (imports.length > 0) {
    lines.push('## Imports (what this component needs)');
    lines.push('');
    lines.push('| From | What | Contract |');
    lines.push('|------|------|----------|');
    for (const d of imports) {
      lines.push(`| ${escapePipes(d.from)} | ${escapePipes(d.what)} | ${escapePipes(d.contract)} |`);
    }
    lines.push('');
  }

  if (exports.length > 0) {
    lines.push('## Exports (what this component provides)');
    lines.push('');
    for (const e of exports) lines.push(`- ${e}`);
    lines.push('');
  }

  appendWarnings(lines, warnings);
  return lines.join('\n');
}

function buildComponentMermaid(x: ComponentExtract): string {
  const out: string[] = ['classDiagram'];
  const cls = toNodeId(x.name || 'Component').replace(/[^A-Za-z0-9_]/g, '_');
  out.push(`  class ${cls} {`);
  for (const t of x.types.slice(0, 8)) {
    // Mermaid class diagram fields — `+` for public
    out.push(`    +${sanitizeForClassBody(t.name)}`);
  }
  for (const f of x.functions.slice(0, 12)) {
    out.push(`    +${sanitizeForClassBody(f.signature)}`);
  }
  if (x.types.length === 0 && x.functions.length === 0) {
    out.push('    %% no extracted members');
  }
  out.push('  }');
  // Import edges
  const seen = new Set<string>();
  for (const imp of x.imports) {
    const src = toNodeId(imp.from);
    if (src === cls || seen.has(src)) continue;
    out.push(`  class ${src}`);
    out.push(`  ${src} <|-- ${cls} : uses ${sanitizeForClassBody(imp.what)}`);
    seen.add(src);
  }
  return out.join('\n');
}

/** classDiagram member lines can't contain `:`, `(`, `)`, etc. — trim. */
function sanitizeForClassBody(s: string): string {
  return s
    .replace(/[(){}:<>]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 60);
}

// ═══════════════════════════════════════════════════════════════════════
//  Integration review
// ═══════════════════════════════════════════════════════════════════════

export function renderIntegrationReview(
  extract: IntegrationExtract,
  specPath: string,
): string {
  const { sharedTypes, contracts, dataFlows, standards, warnings } = extract;

  const lines: string[] = [];
  lines.push('# Integration Specification — Review Summary');
  lines.push('');
  lines.push(`_Auto-generated by spec2 review. Full spec: \`${specPath}\`_`);
  lines.push('');

  lines.push('## Key Facts');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| Shared Types | ${sharedTypes.length} |`);
  lines.push(`| Interface Contracts | ${contracts.length} |`);
  for (const [k, v] of Object.entries(standards)) {
    lines.push(`| Standard — ${k} | ${escapePipes(v)} |`);
  }
  lines.push('');

  lines.push('## Interaction Diagram');
  lines.push('');
  lines.push('```mermaid');
  lines.push(buildIntegrationMermaid(extract));
  lines.push('```');
  lines.push('');

  if (sharedTypes.length > 0) {
    lines.push('## Shared Types');
    lines.push('');
    for (const t of sharedTypes) lines.push(`- ${t}`);
    lines.push('');
  }

  if (contracts.length > 0) {
    lines.push('## Interface Contracts');
    lines.push('');
    for (const c of contracts) {
      lines.push(`### ${c.parties}`);
      if (c.purpose) lines.push(`**Purpose:** ${c.purpose}`);
      if (c.interface) lines.push(`**Interface:** ${c.interface}`);
      lines.push('');
    }
  }

  if (dataFlows) {
    lines.push('## Data Flows');
    lines.push('');
    lines.push(dataFlows);
    lines.push('');
  }

  appendWarnings(lines, warnings);
  return lines.join('\n');
}

function buildIntegrationMermaid(x: IntegrationExtract): string {
  const out: string[] = ['graph LR'];
  const declared = new Set<string>();
  const declare = (raw: string): string => {
    const id = toNodeId(raw);
    if (!declared.has(id)) {
      out.push(`  ${id}["${labelSafe(raw)}"]`);
      declared.add(id);
    }
    return id;
  };

  for (const c of x.contracts) {
    const parties = splitContractParties(c.parties);
    if (!parties) continue;
    const [a, b] = parties;
    const aid = declare(a);
    const bid = declare(b);
    const edgeLabel = c.purpose ? labelSafe(c.purpose).slice(0, 40) : 'contract';
    out.push(`  ${aid} <-->|"${edgeLabel}"| ${bid}`);
  }
  if (x.contracts.length === 0) {
    out.push('  %% No contracts extracted');
  }
  return out.join('\n');
}

// ═══════════════════════════════════════════════════════════════════════
//  Shared helpers
// ═══════════════════════════════════════════════════════════════════════

function escapePipes(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function appendWarnings(lines: string[], warnings: string[]): void {
  if (warnings.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('_Parse warnings (review package is best-effort on malformed specs):_');
    for (const w of warnings) lines.push(`- ${w}`);
    lines.push('');
  }
  lines.push('---');
  lines.push(`_Generated: ${new Date().toISOString()}_`);
}
